# Modelagem

<img src="https://cdnsciencepub.com/cms/10.1139/er-2020-0019/asset/images/large/er-2020-0019f1.jpeg" />

In [ ]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Testes para modelos
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error

In [ ]:
# Leitura das bases
df_train = pd.read_csv('/content/drive/MyDrive/IA/Machine Learning/_focos_treino.csv')
df_test = pd.read_csv('/content/drive/MyDrive/IA/Machine Learning/_focos_teste.csv')

# Objetivo h√° se atingir
y_train = df_train['alvo']
y_test = df_test['alvo']

# Conjunto de treinamento
X_train = df_train.drop('alvo', axis=1)
X_test = df_test.drop('alvo', axis=1)

## *Feature Selection*

In [ ]:
# from sklearn.linear_model import LogisticRegression
# from sklearn.feature_selection import RFE

# model = LogisticRegression(max_iter=1000)
# selected = RFE(model, step = 1, n_features_to_select = 6)
# selected = selected.fit(X_train.iloc[:, :-2], y_train)

# _columns = [X_train.columns[i] for i, c in enumerate(selected.support_) if c]
# X_train, X_test = X_train[_columns], X_test[_columns]

In [ ]:
# from sklearn.feature_selection import SelectKBest, chi2

# selected = SelectKBest(chi2, k = 6).fit(X_train.iloc[:, :-2], y_train)

# X_train = X_train[selected.get_feature_names_out()]
# X_test = X_test[selected.get_feature_names_out()]

In [ ]:
X_train

,ano,mes,dia,hora,minuto,diasemchuva_norm,precipitacao_norm,frp_norm,num_bioma,num_estado,latitude,longitude
0,2019,9,25,18,40,3.0,0,18.500000,0,0,-10.808000,-69.616000
1,2020,8,24,17,7,4.0,0,41.400000,0,21,-9.365000,-64.483000
2,2014,9,22,16,47,2.0,1,29.200000,0,13,-5.613000,-51.658000
3,2019,9,6,18,10,0.0,0,36.894107,0,21,-9.528832,-64.018322
4,2019,11,30,16,50,1.0,1,15.600000,0,10,-11.239000,-51.618000
...,...,...,...,...,...,...,...,...,...,...,...,...
1420030,2020,9,6,16,45,13.0,0,17.200000,0,13,-7.803000,-50.252000
1420031,2015,12,17,17,18,2.0,1,17.800000,0,3,-3.553000,-58.959000
1420032,2022,2,3,17,11,7.0,1,13.500000,4,20,-31.797980,-52.230470
1420033,2019,9,8,16,20,42.0,0,33.200000,2,9,-7.726000,-46.272000
1420034,2020,8,10,18,40,15.0,0,73.050000,0,3,-9.525000,-66.743000

In [ ]:
X_test

,ano,mes,dia,hora,minuto,diasemchuva_norm,precipitacao_norm,frp_norm,num_bioma,num_estado,latitude,longitude
0,2020,7,13,16,40,3.0,0,19.40,0,9,-3.220,-46.341
1,2018,10,6,17,15,0.0,1,41.60,2,10,-13.560,-53.105
2,2019,11,22,16,0,0.0,0,59.50,2,9,-7.744,-45.677
3,2019,8,28,16,40,5.0,0,73.05,0,13,-6.890,-55.118
4,2020,12,17,17,45,3.0,0,10.40,0,21,-12.989,-61.388
...,...,...,...,...,...,...,...,...,...,...,...,...
608582,2015,8,22,16,59,35.0,1,35.05,1,17,-7.095,-42.680
608583,2016,10,13,16,46,4.0,0,30.50,2,26,-8.070,-47.024
608584,2018,10,14,16,25,10.0,1,20.30,3,12,-16.572,-41.975
608585,2021,5,25,17,0,8.0,0,36.20,2,10,-11.135,-51.666
608586,2020,8,5,16,40,35.0,0,73.05,2,11,-21.239,-53.676

## Classifica√ß√£o

In [ ]:
# √Årvore de decis√£o (DT)
from sklearn.tree import DecisionTreeClassifier

dt_classifier = DecisionTreeClassifier(criterion='gini', max_depth=10)

# Treinamento para tomada de decis√µes
dt_classifier = dt_classifier.fit(X_train, y_train)

# Criar predi√ß√£o na base de testes
dt_predict = dt_classifier.predict(X_test)

# Verificar acur√°cia
dt_acc = accuracy_score(dt_predict, y_test)
print("DT Acur√°cia", dt_acc)

DT Acur√°cia 0.8954688608410468

In [ ]:
# K-vizinhos mais pr√≥ximos (KNN)
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=10)

# Treinamento para tomada de decis√µes
knn = knn.fit(X_train, y_train)

# Criar predi√ß√£o na base de testes
knn_predict = knn.predict(X_test)

# Verificar acur√°cia
knn_acc = accuracy_score(knn_predict, y_test)
print("KNN Acur√°cia", knn_acc)

KNN Acur√°cia 0.8942385787671819

## Regress√£o

In [ ]:
# Regress√£o Linear (LR)
from sklearn.linear_model import LinearRegression

lr  = LinearRegression().fit(X_train, y_train)

# Predi√ß√£o para a base teste
lr_predict = lr.predict(X_test)

# Avalia√ß√£o do erro
print("R^2 :", r2_score(y_test, lr_predict))
print("Erro m√©dio absoluto :", mean_absolute_error(y_test, lr_predict))
print("Raiz do Erro Quadr√°tico M√©dio:", np.sqrt(mean_squared_error(y_test, lr_predict)))

R^2 : 0.3674931359180772
Erro m√©dio absoluto : 0.3352917896946605
Raiz do Erro Quadr√°tico M√©dio: 0.3972870682528139

## Multi Layer Perceptrons

In [ ]:
# Rede neural de classifica√ß√£o
from sklearn.neural_network import MLPClassifier

# https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html
clf = MLPClassifier( # Ajustar os hiperparametros
    hidden_layer_sizes = (10, 12, 30, 60, 30, 5, 50, 6, 25),
)
clf = clf.fit(X_train, y_train)

# Predi√ß√£o da rede com a base de teste
clf_predict = clf.predict(X_test)

# Resultado obtido com a predi√ß√£o
clf_acc = accuracy_score(clf_predict, y_test)
print("CLF Acur√°cia", clf_acc)

CLF Acur√°cia 0.831269726493559

## Modelo Selecionado

In [ ]:
'''
  Este algoritmo seleciona √°rvores de decis√£o
  aleat√≥rias em v√°rias subamostras e usa a m√©dia para melhorar
  a precis√£o preditiva e controlar o sobreajuste (overfitting)
'''

# Floresta Aleat√≥ria
from sklearn.ensemble import RandomForestClassifier

# Treinamento para tomada de decis√µes
model = RandomForestClassifier(
    criterion = 'entropy',
    max_depth = 70,
    min_samples_split = 5,
    min_samples_leaf = 5,
).fit(X_train, y_train)

# Criar predi√ß√£o na base de testes
model_predict = model.predict(X_test)

# Verificar acur√°cia
model_acc = accuracy_score(model_predict, y_test)
print("Modelo Acur√°cia:", model_acc)

Modelo Acur√°cia: 0.9496752313145039

In [ ]:
print('Acur√°cia de Treinamento :', accuracy_score(y_train, model.predict(X_train)))
print('Acur√°cia de Teste :', accuracy_score(y_test, model.predict(X_test)))

Acur√°cia de Treinamento : 0.9716330935505111
Acur√°cia de Teste : 0.9496818039162848